name: Continous Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:      
  package:
    name: Package
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.build-image.outputs.image }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        mask-aws-account-id: 'no'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push backend image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: training-cloud-delivery
        IMAGE_TAG: ${{ github.sha }}
        BRANCH_TAG: ${{ env.GITHUB_REF_SLUG }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: training-cloud-delivery
          image: 017255229468.dkr.ecr.us-east-1.amazonaws.com/training-cloud-delivery:main 
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: us-east-1
          cpu : 1
          memory : 2
          # Deprecated: wait-for-service-stability: true
          # The new way to control service stability timeout
          wait-for-service-stability-seconds: 1200
      
      - name: App Runner URL
        run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}" 
      
